export const myData=[
  {
    "Sign In & Register Page": [
      "Sign In",
      "Sign in to your account to continue",
      "Register",
      "Name",
      "First Name",
      "Last Name",
      "PhonEmail Address",
      "Please Enter Email Address",
      "Please Enter Email Addres",
      "Profile Image",
      "Upload Image",
      "Password",
      "Confirm Password",
      "Date of Birth",
      "Gender",
      "Male",
      "Female",
      "Others",
      "Prefer not to respond",
      "Create your account",
      "By Creating an account, I accept ...",
      "Forgot Password",
      "Recover Password",
      "Please enter your email address ....",
      "Back To Login",
      "Reset Password",
      "These credentials do not match our records.",
      "We can't find a user with that e-mail address.",
      "Email or password are wrong",
      "Successfully Login!",
      "Error",
      "Search",
      "Sign Out",
      "Personal Information",
      "Address",
      "Profile"
    ]
  },
  {
    "Community": [
      "Back",
      "Update",
      "Remove",
      "or",
      "Yes",
      "No",
      "Continue",
      "SELECT",
      "Home",
      "Groups",
      "Feed",
      "Members",
      "Channels",
      "Events",
      "Leaderboard",
      " Pending Post",
      "Join Community",
      "Groups in",
      "Visit Group",
      "Posts",
      "Community Info",
      "Join Group",
      "Connexion Privée",
      " Pending",
      "Leave Group",
      " Group Info",
      "Public",
      "Private",
      "My Badges",
      "My Points",
      "Information sur le groupe",
      "Public",
      "Privé",
      "Make a post to get",
      "Comment on a post to get",
      "Like a comment or post to get",
      "Viral share of referral link",
      "Referral Link",
      "Copy",
      "Copied",
      "Earn [points] points for every new sign up to the community through your referral link",
      "Message",
      "Create Post",
      "Write Your Post",
      " Text",
      "Photo",
      "Audio",
      "Video",
      "Tag members",
      "Add Photo",
      "Add Audio",
      "Embed",
      "Video URL",
      "Enter your embed code here",
      "Supported URL: YouTube, Vimeo, Wistia and Custom link",
      "Post",
      "Pinned Post",
      "Unpin",
      " Pin",
      "Edit",
      "Delete",
      " Approve",
      " Reject",
      " Like",
      " Share",
      " SHARE POST",
      " Reply",
      " View Reply",
      " Add your comment",
      " View More Comments",
      " No Post Found",
      " No Data Found",
      "Find Member",
      "Name",
      "Comments",
      "Likes",
      "Member Info",
      "Chat Now",
      "No Member Found",
      "Joined",
      "Admin",
      "Moderator",
      "Blogs",
      "Resources",
      "Assets",
      "Course",
      "No Channel Found",
      " Please Join the group to make a post, view channels and events",
      " Earn [points] points to unlock this channel",
      "Google Meet",
      "Zoom",
      "Webinar",
      "Live Event",
      "Position",
      "Points",
      "Badges",
      "Activity",
      "Admin will review your post and approve. Until then your post to the group will be pending.",
      "Admin will review your info and approve. Until then your access to the group will be pending.",
      "This group is private Join to view or discuss",
      "Successfully Joined",
      " Successfully Left.",
      "Successfully Shared",
      "Successfully Signed Up",
      "Successfully Saved",
      "Successfully Updated",
      "Successfully Pinned",
      "Successfully UnPinned",
      "Are you sure, Do you want to delete this post?",
      " Are you sure, Do you want to delete this comment?",
      "Are you sure, Do you want to Reject this comment?",
      "Are you sure, Do you want to Approve this Post?",
      "Successfully Approved",
      "Approve Confirmation",
      " Delete Confirmation",
      "Maximum member limit reached. Please contact support for further assistance.",
      "Your access to the group is restricted. Please reach out admin for further assistance.",
      "Account Already Exist",
      "[name] commented on your post.",
      "[name] replied to your comment.",
      "[name] liked your post.",
      "[name] liked your comment.",
      "[name] tagged you in a post",
      "[name] Sent you a private message",
      "No Notification Found",
      "You have [count] new notification",
      "Recent Notification",
      "and",
      "others",
      "Done",
      "Done",
      "[time] years ago",
      "[time] hours ago",
      "[time] days ago",
      "[time] minutes ago",
      "[time] seconds ago",
      "Just Now",
      "Checkout Page"
    ]
  },
  {
    "Checkout Page": [
      "Cancel and return to community",
      "Payment Options",
      "Payment details",
      "Total",
      "VAT",
      "This is a one time payment",
      "Each order is processed through a secure, 256-bit encrypted ...",
      "Buy Now",
      "No Payment option available"
    ]
  },
  {
    "Manual Payment": [
      "Manual Payment",
      "Account Name",
      "Account Number",
      "Name Of The Bank",
      "Swift code",
      "Company Name",
      "ABA Number",
      "Payment URL",
      "Visit",
      "Cash on delivery",
      "Are you sure, You want to proceed ....",
      "Click here to Manual Payment Details"
    ]
  },
  {
    "Payment Page": [
      " Proceed",
      "Thank You",
      " Payment Successful",
      " You will receive email...",
      " You can also check...",
      " NAME ON CARD",
      " CARD NUMBER",
      "EXPIRATION MONTH",
      " CVC",
      " EXPIRATION YEAR",
      " PAY NOW",
      " Secure Checkout",
      "Please correct the errors and try again",
      "Payment Failed,Please Try again",
      "Sorry"
    ]
  },
  { "My Orders": ["My orders", "No orders yet"] }
] as const
